FROM node:20-alpine

WORKDIR /app

COPY ./backend .

RUN mkdir .bin
RUN mkdir .tmp
RUN apk add --update python3
RUN wget https://github.com/yt-dlp/yt-dlp/releases/download/2024.07.09/yt-dlp -P .bin
RUN chmod u+rwx .bin/yt-dlp
RUN yarn install
RUN yarn run build

ENV NODE_ENV=production

ENTRYPOINT [ "node" ]

CMD [ "." ]
