services:
  backend:
    build:
      dockerfile: dockerfile.backend
    environment:
      TMPDIR: /app/.tmp/
  frontend:
    build:
      dockerfile: dockerfile.frontend
    environment:
      BACKEND_URL: http://backend:3001
    ports:
      - 80:3000
    depends_on:
      - backend
